imports:
    - { resource: framework_prod.yml }

framework:
    profiler:
        only_exceptions: false
    session:
        save_path: %kernel.root_dir%/sessions
    templating:
        assets_base_url: "http://localhost:8080"
